spring:
  datasource:
    #dataSource
    url: jdbc:mysql://localhost:3306/hw?serverTimezone=Asia/Taipei
    username: root
    password: root
  jpa:
    #sessionFactory
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

#server
server:
  port: 8081
  servlet:
    context-path: /boot

